version: "3.9"

services:
  # Phân hệ API Server (Backend)
  backend:
    build: .
    container_name: DATN_backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - /app/node_modules # Tránh ghi đè thư mục node_modules từ local máy chủ
    command: npm start

  # Phân hệ Giao diện Web (React Frontend)
  frontend:
    build: ../frontend
    container_name: DATN_frontend
    ports:
      - "5173:80"
    restart: always
    environment:
      - VITE_URL_LINKS=http://localhost:3000/api/v1/
